### ISSUE TITLE
tapToClose not working on device

### ISSUE THREAD

**Issue by alphasp** [root-two/react-native-drawer#174]
When drawer is open, tap on right side will not close drawer on device (iPhone 6s plus), but works on simulator.
`if (gestureState.moveX < 125) this.processTapGestures()` in [onPanResponderRelease](https://github.com/root-two/react-native-drawer/blob/master/index.js#L286)
Based on my finding, I noticed that the value in gestureState.moveX is always 0 in simulator while on my iphone return value more than 0 up to 375 depending on position that i tapped

**Comment by Sh3rawi** [comment]
I can confirm this is happening on Android as well - Simulator works just fine but on real device it does not work.
This is the commit that caused this behaviour: https://github.com/root-two/react-native-drawer/commit/23411f836f98b327516a70f7899b0bc6b7a2abc0
This whole comparison to moveX was not in 2.0.0 but got inserted with this commit to 2.1.0 (2.0.0 works fine but anything after it does not).

**Comment by ms88privat** [comment]
👍

**Comment by gerard0315** [comment]
not working on iOS device here as well

**Comment by richarddlu** [comment]
It works for me on real iphone6 with IOS 9.3.2, but does not work for real Android device with Android version 5.0.

**Comment by rt2zz** [comment]
right now we check the gesture move delta to decide if it is a tap. My thought it we should actually be checking the duration as that is probably a more reliable metric.

**Comment by Valentin-Laurent** [comment]
I get the purpose of `gestureState.moveX < 125`, but it doesn't seem to be reliable.
On emulators, this value is always 0, and on devices (debug mode), the value is 0 on my Nexus 5X and is above 125 on Samsung devices. 

I've created a PR (https://github.com/root-two/react-native-drawer/pull/177) that removes this condition, and it fixes the bug, at least on Samsung S4, S6, Nexus 5X, and iPhone 5s.

By the way, I think you're right about the duration, because my fix is a bit brutal since the menu will close even if you swipe it back to the right.

**Comment by luisfuertes** [comment]
I have "react-native-drawer": "^2.2.2" and in device Zuk Z1 and Samsung Galaxy S3 it does not work

**Comment by nasal** [comment]
If it helps someone who has time to check, `tapToClose` works if the drawer is positioned on the right with `side="right"`.

**Comment by luisfuertes** [comment]
With `side="right"` `tapToClose`works on my Android device.

**Comment by alphasp** [comment]
fixed in latest version@2.3.0

**Comment by franzejr** [comment]
@alphasp are you sure it's working on the @2.3.0? It seems, it's not working on iOS

**Comment by alphasp** [comment]
@franzejr yes, it is working on both iOS and Android devices for me
