### ISSUE TITLE
Changing the side property does not work

### ISSUE THREAD

**Issue by rclai** [root-two/react-native-drawer#207]
I'm trying to implement a two-sided drawer by simply switching the `side` property from `left` to `right` and switching the `content` based on what `side` is. However, I noticed that the underlying `StyleSheet` is not updated when you change the `side` property.

**Comment by akrumel** [comment]
I needed this feature as well so took a look at the code. The following changes enables dynamically switching drawer sides:
1. initialize(props) function 
   
   a. change all references to 'this.props' to 'props'
   b. move line 'this.stylesheet = StyleSheet.create(styles)' to after the if check in which it is contained.
2. componentWillReceiveProps() - comment out the 'this.requiresResync()' check line and add a call at end of function to 'this.initialize(nextProps)'. 

The requiresResync()/resync() combination can be commented out since resync() is invoked at the end of initialize(). 

initialize() needs to be invoked on properties change since styles need to be updated to match latest properties.

**Comment by rclai** [comment]
I ended up creating my own drawer, which was more lean but thanks.
