### ISSUE TITLE
`tapToClose` prop can glitch animation if you drag a really short distance

### ISSUE THREAD

**Issue by felixakiragreen** [root-two/react-native-drawer#47]
Here is a preview of what I'm talking about:

It's dropped some frames (it glitches back and forth more times than once) but the gif still shows it.

**Comment by rt2zz** [comment]
Yes, I put in a little [naive time delta check](https://github.com/rt2zz/react-native-drawer/blob/master/index.js#L358) to try and avoid this, but clearly that is not enough. I think a better approach would be to check the distance travelled rather than the tap duration.

Question: intuitively do you expect the drawer to open or close in this situation where `tapToClose=true` but a short drag was detected?

**Comment by felixakiragreen** [comment]
Intuitively I feel open. But that depends on the distance travelled. It's a tough one. If it's really really short then it shouldn't open, but it also shouldn't count as a `tap` because distance was travelled. I think taps don't travel any distance.

**Comment by navdove** [comment]
hey dubert, i am facing another issue on first time tap stutter and drawer doesn't close. i created an issue https://github.com/rt2zz/react-native-drawer/issues/51

can you check in your code such behaviour? Also can you pl review my code pasted in the issue on how i am navigating to different views on menu taps.

thanks-in-advance.

**Comment by rt2zz** [comment]
fixed. a tap is now considered when the distance travelled is < 50 and the time travelled is < 350.

Additionally when a "tap" is detected no pan events are triggered (thus avoiding the conflicting actions originally observed)

Fix is in v1.9.0. Please test and let me know how that goes.
