### ISSUE TITLE
Drawer gets "stuck" when dragging past the edge

### ISSUE THREAD

**Issue by jmstout** [root-two/react-native-drawer#6]
I haven't looked into what might be causing this problem, but I thought it should be brought to your attention.

When dragging the drawer, opening or closing, if you quickly swipe past the edge of the screen, sometimes it will get stuck.

It also becomes unresponsive to further drag attempts in the same direction, but does allow you to move the drawer in the opposite direction.

Here are some screenshots of what I'm referring to:

![image](https://cloud.githubusercontent.com/assets/817658/7421382/f74a1608-ef51-11e4-8e37-38920b07e8b6.png)
![image](https://cloud.githubusercontent.com/assets/817658/7421383/fd8b34de-ef51-11e4-8b62-60acb9bea249.png)

**Comment by rt2zz** [comment]
Hmm. are you on v1.0.4 ? I recently fixed a bug where it was throttling the animations, and would sometimes result in the animation not completing. 

Because you mention it being unresponsive to further drags in the same direction that leads me to believe the drawer is toggled, just the animation did not complete.

**Comment by jmstout** [comment]
Yeah, it's definitely still happening in v1.0.4. It's especially easy to trigger when testing on a device.

What you mentioned about the animation not completing makes a lot of sense.

It almost seems like the animation is being canceled when your finger crosses the edge of the screen into the bezel.

**Comment by rt2zz** [comment]
Ok that helps, I will try later today on an iphone

**Comment by rt2zz** [comment]
Ok, I was still unable to reproduce the issue, but while digging I found a bunch of other issues that I have now resolved in the latest version (1.0.6)

Among the issues was that I had an old version of rn-drawer in the demo app, so I suspect this was the cause.

Let me know if this solves it :)

**Comment by jmstout** [comment]
Alas, unfortunately the issue still persists. To be sure I was running the latest version, I downloaded a fresh version of your project and double checked that it was 1.0.6.

I'm not sure why you can't reproduce the issue. I can't think of anything that would be uniquely causing the issue on my setup.

I've captured some footage so you know I'm not just crazy ;)
[rn-drawer-glitch-1.mov](https://dl.dropboxusercontent.com/u/117695213/static/rn-drawer-glitch-1.mov)
[rn-drawer-glitch-2.mov](https://dl.dropboxusercontent.com/u/117695213/static/rn-drawer-glitch-2.mov)

Thanks for looking into this, I really appreciate it!

**Comment by rt2zz** [comment]
Thanks @jmstout - turns out I do this funky two finger tackpad drag which prevented me from reproducing. Now that I am doing one finger drags, I see the problem. I believe c999f8c fixes this.

Basically it would not complete the animation if the pan was travelling in the wrong direction. Now it will always either open or close the drawer on pan end, depending on the x position.

**Comment by jmstout** [comment]
@rt2zz - just got a chance to test your latest fix and I'm no longer having the problem. Well done!

Thanks for all your hard work figuring this one out :smile:  :+1:
