### ISSUE TITLE
Drag to open drawer captured (& lost) to ListView

### ISSUE THREAD

**Issue by felixakiragreen** [root-two/react-native-drawer#60]
I have a Drawer and inside it a Navigator. When the Navigator is rendering a ListView, I can swipe backwards below the rows (if they don't go to the bottom of the screen) and it will open the drawer, but if I try to do it over the rows, it's captured as a RowPress and the navigator pushes the next route.

I know there is a CaptureGestures prop, but then it seems like there is a ton of necessary logic around allowing the gesture to pass though in every other scenario but I'm not sure how to do it.

One thought I had was to insert a View over the left portion of the screen above the ListView that attempted to conditionally capture the gestures, but then I don't know how to pass that to the Drawer.

Is there a better way? Thoughts on the right way to solve this?

**Comment by rt2zz** [comment]
I believe `captureGestures={true}` is what you want. You should not have to do any additional logic, all captureGestures does is use the capture method of the [pan responder](http://facebook.github.io/react-native/docs/panresponder.html#content). In react native children by default get first dibs on responding to a pan, but if you set capture the parent gets first dibs.

The only time captureGestures is bad is if you specifically need buttons to be clickable underneath your pan mask.

Hopefully this makes sense, let me know how that goes.

**Comment by rt2zz** [comment]
Ah I just read your comment a little more, can you clarify:

Do you want gestures to pass through in all cases except for when there is a list view?

**Comment by felixakiragreen** [comment]
Basically, yes.

**Comment by felixakiragreen** [comment]
But if I conditionally allow capturing like `captureGestures={routeIsListView}` I still encounter the problem where the user can't press the back button in the titlebar because the gesture is captured.

**Comment by rt2zz** [comment]
Ok I understand, let me think about this. For a short term solution I would recommend setting `panOpenMask={5}` which will effectively be so small that on screen taps are unlikely to trigger it while a swipe still should.

**Comment by toadums** [comment]
@dubert Is there any way that you can move the drawer to be nested inside the navigator? I can't remember what problem I was having exactly (it was a few months ago), but it sounds similar to this - trying to render the Drawer as the root component of my app created strange gesture related issues. What I did to get around it was something like this:

``` es6
class Navigation {
  renderScene = (route, navigator) => {
    // Get _component and navbar however

    const child = (
      <View style={{ flex: 1 }}>
        {navbar}
        <_component {...someProps} />
      </View>
    );

    // showDrawer determines if we are rendering a root view,
    // or a view that should have a back button
    return this.showDrawer() ?
      <Drawer {...drawerProps}>{child}</Drawer>
    : child;
  }

  render() {
    return (
      <Navigator renderScene={this.renderScene} />
    );
  }
}
```

And for completeness, in my root component that is rendered by the drawer, I have some logic that applies a transparent mask over the content when the drawer is open, so that the only 'gesturable' content on the screen is the drawer itself. I didn't like setting `captureGestures` conditionally - it didn't work very well for my use case.

Not sure if this will fix your problem, but maybe it will help you find the solution.. :)

**Comment by rt2zz** [comment]
@toadums thanks for the info. If you find an elegant solution to these use cases let me know and we can integrate it into the module proper.

@dubert I usually set `captureGestures` true all of the time. Your back button should still be pressable as long as you have a top margin on your drawer style (i.e. `styles={drawer:{marginTop:30}}`), although this requires confirmation.

One other approach you might try is to set `negotiatePan={true}` and `captureGestures={true}`. negotiatePan prop was added to help the drawer coexist with scroll views, but because of the way it works there is a small chance it might help your use case.

**Comment by rt2zz** [comment]
Closing as there have been many improvements to captureGestures since Jan. Please reopen if there is still an issue.
